# Generated by Django 4.2 on 2024-10-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image_long',
            new_name='image_serv',
        ),
    ]
