# Generated by Django 4.2 on 2024-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingz',
            name='long_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
