# Generated by Django 4.2 on 2024-10-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingz', '0002_settingz_long_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingz',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settingz',
            name='image',
            field=models.ImageField(default='12:00:00', upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
