# Generated by Django 4.2 on 2024-10-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutus_image_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='feature4',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='feature5',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='feature6',
        ),
    ]
